fix: bumping lerna version and catching lerna errors

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -100,8 +100,15 @@ jobs:
 
           echo "lernaCommand: ${lernaCommand}"
 
+          lernaOutput=$(pnpm --silent lerna ${lernaCommand} --l --json 2>lerna_error.txt| jq -r '.[].location' || true)
+          if [[ $(cat lerna_error.txt|grep "ERR!") ]]; then
+            echo "Error executing lerna command:"
+            cat lerna_error.txt
+            exit -1
+          fi
+
           # Verify no packages exist from the `@kong-ui` scope; if yes, then exit with error
-          for packageLocation in $(pnpm --silent lerna ${lernaCommand} --l --json | jq -r '.[].location')
+          for packageLocation in ${lernaOutput}
           do
             packageName=$(jq -r '.name' "$packageLocation"/package.json)
             publishConfigAccess=$(jq -r '.publishConfig.access' "$packageLocation"/package.json)
@@ -138,8 +145,15 @@ jobs:
           componentTestFilter=""
           componentTestMatrix=""
 
+          lernaOutput=$(pnpm --silent lerna ${lernaCommand} --l --json 2>lerna_error.txt| jq -r '.[].location' || true)
+          if [[ $(cat lerna_error.txt|grep "ERR!") ]]; then
+            echo "Error executing lerna command:"
+            cat lerna_error.txt
+            exit -1
+          fi
+
           # get the list of changed packages, grab the location
-          for pkgFolder in $(pnpm --silent lerna ${lernaCommand} --l --json|jq -r '.[].location')
+          for pkgFolder in ${lernaOutput}
           do
             # remove current folder from the location path
             pkgFolder="${pkgFolder/$(pwd)\//}"
@@ -240,7 +254,13 @@ jobs:
 
           git checkout "${{ github.head_ref }}"
 
-          versions=$(pnpm --silent lerna version prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --conventional-prerelease --yes --amend --json --no-git-tag-version || true)
+          versions=$(pnpm --silent lerna version prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --conventional-prerelease --yes --amend --json --no-git-tag-version 2>lerna_error.txt || true)
+          if [[ $(cat lerna_error.txt|grep "ERR!") ]]; then
+            echo "Error executing lerna command:"
+            cat lerna_error.txt
+            exit -1
+          fi
+
           if [[ "${versions}" == "" ]]; then
             echo "no packages to version"
             exit 0
@@ -410,7 +430,13 @@ jobs:
           git config user.email "konnectx-engineers+kongponents-bot@konghq.com"
           git config user.name "Kong UI Bot"
 
-          versions=$(pnpm --silent lerna version --conventional-commits --create-release github --yes --force-git-tag --json || true)
+          versions=$(pnpm --silent lerna version --conventional-commits --create-release github --yes --force-git-tag --json 2>lerna_error.txt || true)
+          if [[ $(cat lerna_error.txt|grep "ERR!") ]]; then
+            echo "Error executing lerna command:"
+            cat lerna_error.txt
+            exit -1
+          fi
+
           if [[ "${versions}" == "" ]]; then
             echo "no packages to version"
             exit 0
